### ISSUE TITLE
 [MultiBuildBeta] IndexOutOfRangeException @NearColliderLogic

### ISSUE THREAD

**Issue by EJaxx** [DysonSphereMod/QOL#42]
happens randomly (0-1/min) when selecting a build position in any mode, Shift+LMouse or blueprint and even the remnants of the blueprint.
I cannot reproduce the error immediately after restarting.
maybe "private static int[] _nearObjectIds = new int[128];" -> 4096 as in the original

1)
```
Exception hit 4 times: IndexOutOfRangeException: Array index is out of range.
NearColliderLogic.GetBuildingsInAreaNonAlloc (UnityEngine.Vector3,single,int[],bool) <0x00ad9>
com.brokenmass.plugin.DSP.MultiBuild.BlueprintManager.Paste (UnityEngine.Vector3,single,bool) <0x01632>
com.brokenmass.plugin.DSP.MultiBuild.BuildLogic.PlayerAction_Build_DetermineBuildPreviews_Prefix (PlayerAction_Build&) <0x01a61>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..DetermineBuildPreviews> (PlayerAction_Build) <0x00b92>
com.brokenmass.plugin.DSP.MultiBuild.BuildLogic.PlayerAction_Build_BuildMainLogic_Prefix (PlayerAction_Build&) <0x001dc>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..BuildMainLogic> (PlayerAction_Build) <0x00023>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..GameTick> (PlayerAction_Build,long) <0x0037f>
PlayerController.GameTick (long) <0x0013f>
Player.GameTick (long) <0x0006c>
(wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x00110>
GameMain.FixedUpdate () <0x00262>

Target methods matching by name:
System.Void PlayerAction_Build::DetermineBuildPreviews()
System.Void PlayerAction_Build::BuildMainLogic()
virtual System.Void PlayerAction_Build::GameTick(System.Int64 timei)
System.Void GameData::GameTick(System.Int64 time)

Relevant plugins:
1. com.brokenmass.plugin.DSP.MultiBuildBeta - brokenmass-MultiBuildBeta-2.1.4\MultiBuild.dll
	Postfix[index=0]: static System.Boolean com.brokenmass.plugin.DSP.MultiBuild.BuildLogic::PlayerAction_Build_DetermineBuildPreviews_Prefix(PlayerAction_Build& __instance)

==================
```
2)
```
Exception hit 8 times: IndexOutOfRangeException: Array index is out of range.
com.brokenmass.plugin.DSP.MultiBuild.BuildLogic.ActivateColliders (NearColliderLogic&,System.Collections.Generic.List`1<UnityEngine.Vector3>) <0x0015b>
com.brokenmass.plugin.DSP.MultiBuild.BlueprintManager.Paste (UnityEngine.Vector3,single,bool) <0x01a05>
com.brokenmass.plugin.DSP.MultiBuild.BuildLogic.PlayerAction_Build_DetermineBuildPreviews_Prefix (PlayerAction_Build&) <0x01a61>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..DetermineBuildPreviews> (PlayerAction_Build) <0x00b92>
com.brokenmass.plugin.DSP.MultiBuild.BuildLogic.PlayerAction_Build_BuildMainLogic_Prefix (PlayerAction_Build&) <0x001dc>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..BuildMainLogic> (PlayerAction_Build) <0x00023>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..GameTick> (PlayerAction_Build,long) <0x0037f>
PlayerController.GameTick (long) <0x0013f>
Player.GameTick (long) <0x0006c>
(wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x00110>
GameMain.FixedUpdate () <0x00262>

Target methods matching by name:
System.Void PlayerAction_Build::DetermineBuildPreviews()
System.Void PlayerAction_Build::BuildMainLogic()
virtual System.Void PlayerAction_Build::GameTick(System.Int64 timei)
System.Void GameData::GameTick(System.Int64 time)

Relevant plugins:
1. com.brokenmass.plugin.DSP.MultiBuildBeta - brokenmass-MultiBuildBeta-2.1.4\MultiBuild.dll
	Postfix[index=0]: static System.Boolean com.brokenmass.plugin.DSP.MultiBuild.BuildLogic::PlayerAction_Build_DetermineBuildPreviews_Prefix(PlayerAction_Build& __instance)

==================
```

**Comment by brokenmass** [comment]
thanks. i think i have a solution for this bug already and i will release it soon

**Comment by brokenmass** [comment]
should be fixed in 2.2.0

**Comment by callmephil** [comment]
@brokenmass This issue is still happening when you try to write a blueprint and one of the building is not yet built (when it's still green) on 2.2.0
